[tool.pyright]
typeCheckingMode = "strict"
venvPath = "."
venv = "venv"

# ESSENCIAL para Django (usa django-stubs)
useLibraryCodeForTypes = true

# Para evitar falsos positivos comuns
reportMissingTypeStubs = false
reportUnknownVariableType = false
reportUnknownMemberType = false

# Ignorar arquivos que n√£o fazem sentido tipar
exclude = [
  "**/migrations/**",
  "**/__pycache__/**",
]
